from snakemake.utils import min_version
min_version("7.0")

import pandas as pd
import numpy as np
import os
import yaml


conda: "mamba"

include: os.path.join("rules", "utils.smk")

## Update paths in the config to be compatible with github submodules
# Need to manually make results_dir an absolute path since above may
# not work if results_dir folder isn't created
# If results_dir is already an absolute path, this is a no-op
config = make_paths_absolute(config, os.getcwd())
config["results_dir"] = os.path.join(os.getcwd(), config["results_dir"])

## Define global variables
if "IGV_dir" in config:
	IGV_DIR = config["IGV_dir"]
else:
	IGV_DIR = config["results_dir"]


if "fragments_preprocessed" not in config:
	config["fragments_preprocessed"] = False

if "RNA_matrix_filtered" not in config:
	config["RNA_matrix_filtered"] = True

RESULTS_DIR = config["results_dir"]
SCRIPTS_DIR = os.path.join(os.getcwd(), "workflow", "scripts")
CELL_CLUSTER_DF = pd.read_table(config["cell_clusters"]).set_index("cluster", drop=False)
WORKFLOW_DIR = os.getcwd()
MODEL_DIR = config["model_dir"]

## Convert cell cluster config to a biosample config for the ABC pipeline
## Treat each cell cluster as a distinct biosample
config["ABC_BIOSAMPLES"] = os.path.join(
	RESULTS_DIR,
	"tmp",
	"config_abc_biosamples.tsv"
	)
make_biosample_config(
	config["cell_clusters"],
	config["ABC_BIOSAMPLES"],
	RESULTS_DIR
)

## Import ABC pipeline as a reusable module
abc_config = get_abc_config(config, config["abc_dir"])

module ABC:
	snakefile:
		os.path.join(config["abc_dir"], "workflow", "Snakefile")
	config: abc_config

## Update scE2G config with consistent references
config = update_scE2G_config(config, abc_config, config["abc_dir"])

## Include Snakemake rules from ABC (excluding all to use only as utility)
use rule * from ABC exclude all as abc_*

# Expand biosamples config
BIOSAMPLE_DF = ABC.enable_retry(
	pd.read_table,
	func_args={'filepath_or_buffer': config["ABC_BIOSAMPLES"]}
)
BIOSAMPLE_DF = expand_biosample_df(BIOSAMPLE_DF)

# Compute feature requirements upfront by reading model feature tables
# This replaces the checkpoint-based feature detection
(BIOSAMPLE_NEEDS_ARC,
 BIOSAMPLE_NEEDS_NUMCANDIDATEENHGENE,
 BIOSAMPLE_NEEDS_NUMTSSENHGENE,
 BIOSAMPLE_NEEDS_NEARBYENHANCERS) = compute_biosample_feature_requirements(BIOSAMPLE_DF)

# Define ABC_BIOSAMPLES_DIR mapping (each biosample's ABC output directory)
ABC_BIOSAMPLES_DIR = {biosample: os.path.join(RESULTS_DIR, biosample) for biosample in BIOSAMPLE_DF["biosample"]}

## Include E2G rules (consolidated from ENCODE_rE2G)
include: os.path.join("rules", "e2g_genomewide_features.smk")
include: os.path.join("rules", "e2g_predictions.smk")

## Include additional Snakemake rules
include: os.path.join("rules", "frag_to_tagAlign.smk")
include: os.path.join("rules", "make_kendall_pairs.smk")
include: os.path.join("rules", "generate_atac_matrix.smk")
include: os.path.join("rules", "compute_kendall.smk")
include: os.path.join("rules", "arc_e2g.smk")
include: os.path.join("rules", "add_external_features.smk")
include: os.path.join("rules", "sc_predictions.smk")
include: os.path.join("rules", "save_configs.smk")


## Define the final outputs of the pipeline
output_files = [os.path.join(RESULTS_DIR, "config", "expanded_biosample_config.tsv")]

biosample_model = list(zip(BIOSAMPLE_DF["biosample"], BIOSAMPLE_DF["model_dir_base"]))
biosample_model_threshold = list(zip(BIOSAMPLE_DF["biosample"], BIOSAMPLE_DF["model_dir_base"], BIOSAMPLE_DF["model_threshold"]))

encode_e2g_predictions = [os.path.join(RESULTS_DIR, biosample, model_name, "encode_e2g_predictions.tsv.gz") for biosample,model_name in biosample_model]
prediction_stats = [os.path.join(RESULTS_DIR, biosample, model_name, f"encode_e2g_predictions_threshold{threshold}_stats.tsv") for biosample,model_name,threshold in biosample_model_threshold]
gene_lists = [os.path.join(RESULTS_DIR, biosample, model_name, "scE2G_gene_list.tsv.gz") for biosample,model_name in biosample_model]
element_lists = [os.path.join(RESULTS_DIR, biosample, model_name, "scE2G_element_list.tsv.gz") for biosample,model_name in biosample_model]
all_qc = os.path.join(RESULTS_DIR, "qc_plots", "predictions_qc_report.html")

bedpe_files = [os.path.join(IGV_DIR, biosample, model_name, f"encode_e2g_predictions_threshold{threshold}.bedpe") for biosample,model_name,threshold in biosample_model_threshold]
atac_bw = [os.path.join(IGV_DIR, biosample, "ATAC.bw") for biosample in BIOSAMPLE_DF["biosample"]]
atac_bw_norm = [os.path.join(IGV_DIR, biosample, "ATAC_norm.bw") for biosample in BIOSAMPLE_DF["biosample"]]

model_perf = os.path.join(RESULTS_DIR, "crispr_benchmarking_performance_summary.tsv")



## Choose relevant output files
output_files.extend(encode_e2g_predictions)
output_files.extend(prediction_stats)
output_files.append(gene_lists)
output_files.append(element_lists)
output_files.append(all_qc)

if config["make_IGV_tracks"]:
	output_files.extend(bedpe_files)
	#output_files.extend(atac_bw) # just output normalize!
	output_files.extend(atac_bw_norm)

if config["benchmark_performance"]:
 	output_files.append(model_perf)

rule all:
	input: 
		output_files
		
