
### INPUT
cell_clusters: "config/config_cell_clusters.tsv"

### OUTPUT
results_dir: "results/2025_0124_chr22p_test/"
IGV_dir: "results/example_results/"

### OPTIONS
benchmark_performance: False # only set to True if all clusters are K562
make_IGV_tracks: False # create ATAC bw and prediction bedpe files?
# only set this to True if you are sure that your fragment files (1) are sorted  with sort -k1,1 2n,n and (2) only contain fragments on chromosomes in the chromosome sizes reference file (default if not specified: False)
fragments_preprocessed: False
# set this to True if the RNA matrix contains the exact set of cells as the ATAC fragment file, and False if it contains more cells (default if not specified: True)
RNA_matrix_filtered: True

### REFERENCE FILES
gene_annotations: "resources/genome_annotations/gencode.v43.chr_patch_hapl_scaff.annotation.gtf.gz" # compatible with RNA matrix
gene_TSS500: "resources/genome_annotations/CollapsedGeneBounds.hg38.intGENCODEv43.TSS500bp.bed" # gene list with promoter bounds
genes: "resources/genome_annotations/CollapsedGeneBounds.hg38.intGENCODEv43.bed" # gene list with gene body bounds 
crispr_dataset: "resources/EPCrisprBenchmark_ensemble_data_GRCh38.intGENCODEv43.tsv.gz" # crispr training data
reference_clusters:  "resources/reference_qc_metrics_sheth_qiu_2024.tsv"

### SUBMODULE PARAMS 
encode_re2g_dir: "ENCODE_rE2G"
model_dir: "models/"
reference_features: ["numTSSEnhGene", "distance", "activity_base", "TargetGenePromoterActivityQuantile", "numNearbyEnhancers", "sumNearbyEnhancers", "is_ubiquitous_uniform", "P2PromoterClass", "numCandidateEnhGene", "hic_contact_pl_scaled_adj", "ABC.Score", "ABC.Numerator", "ABC.Denominator", "normalized_dhs_prom", "normalized_dhs_enh", "normalized_atac_prom", "normalized_atac_enh", "Kendall", "ARC.E2G.Score"]
final_score_col: "E2G.Score.qnorm"
