
### INPUT
cell_clusters: "/oak/stanford/groups/engreitz/Users/rosaxma/github_repos_2/sc-E2G/run/test_merge_250220/config/config_cell_clusters.tsv"

### OUTPUT
results_dir: "/oak/stanford/groups/engreitz/Users/rosaxma/github_repos_2/sc-E2G/run/test_merge_250220/results/results/"
IGV_dir: "/oak/stanford/groups/engreitz/Users/rosaxma/github_repos_2/sc-E2G/run/test_merge_250220/results/IGV/"

### OUTPUT OPTIONS
benchmark_performance: False # only set to True if all clusters are K562
make_IGV_tracks: False # create ATAC bw and prediction bedpe files?

### REFERENCE FILES
gene_annotations: "/oak/stanford/groups/engreitz/Users/rosaxma/github_repos_2/sc-E2G/resources/genome_annotations/gencode.v43.chr_patch_hapl_scaff.annotation.gtf.gz" # compatible with RNA matrix
gene_TSS500: "/oak/stanford/groups/engreitz/Users/rosaxma/github_repos_2/sc-E2G/resources/genome_annotations/CollapsedGeneBounds.hg38.intGENCODEv43.TSS500bp.bed" # gene list with promoter bounds
genes: "/oak/stanford/groups/engreitz/Users/rosaxma/github_repos_2/sc-E2G/resources/genome_annotations/CollapsedGeneBounds.hg38.intGENCODEv43.bed" # gene list with gene body bounds 
crispr_dataset: "/oak/stanford/groups/engreitz/Users/rosaxma/github_repos_2/sc-E2G/resources/EPCrisprBenchmark_ensemble_data_GRCh38.intGENCODEv43.tsv.gz" # crispr training data

### SUBMODULE PARAMS 
encode_re2g_dir: "/oak/stanford/groups/engreitz/Users/rosaxma/github_repos_2/sc-E2G/ENCODE_rE2G"
model_dir: "models/"
reference_features: ["numTSSEnhGene", "distance", "activity_base", "TargetGenePromoterActivityQuantile", "numNearbyEnhancers", "sumNearbyEnhancers", "is_ubiquitous_uniform", "P2PromoterClass", "numCandidateEnhGene", "hic_contact_pl_scaled_adj", "ABC.Score", "ABC.Numerator", "ABC.Denominator", "normalized_dhs_prom", "normalized_dhs_enh", "normalized_atac_prom", "normalized_atac_enh", "Kendall", "ARC.E2G.Score"]
final_score_col: "E2G.Score.qnorm"
